/**
 * Drives the real Concrete CMS block in a DOM, with the real dist bundle
 * loaded the way the browser loads it, and checks what the page displays
 * against fixtures generated by the Python reference.
 *
 *   python3 tests/make_fixtures.py        # writes tests/fixtures.json
 *   node tests/browser_test.js
 */
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

const ROOT = path.join(__dirname, '..');
const blockHtml = fs.readFileSync(path.join(ROOT, 'web', 'sizing-tool-block.html'), 'utf8');
const bundle = fs.readFileSync(path.join(ROOT, 'dist', 'usg-all-models.js'), 'utf8');
const fixtures = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures.json'), 'utf8'));

const PIPE_OPTIONS = ["N/A", '3/8"', '1/2"', '3/4"', '1"', '1-1/4"', '1-1/2"', '2"', '2-1/2"', '3"'];

let pass = 0, fail = 0;
function check(name, cond, extra) {
  if (cond) { pass++; console.log('  PASS', name); }
  else { fail++; console.log('  FAIL', name, extra === undefined ? '' : String(extra).slice(0, 400)); }
}

// Build a page: the CDN <script> is replaced with the local bundle (same code,
// no network), everything else is byte-for-byte the block that gets pasted in.
function makePage(opts) {
  opts = opts || {};
  let html = blockHtml.replace(/<script src="https:\/\/cdn\.jsdelivr\.net[^"]*"><\/script>/,
    opts.omitAlgorithm ? '' : '<script>' + bundle + '</script>');
  html = html.replace(/<script src="https:\/\/cdnjs[^"]*"><\/script>/, ''); // jsPDF: not needed here
  const dom = new JSDOM('<!doctype html><html><body>' + html + '</body></html>', {
    runScripts: 'dangerously',
    url: 'https://hollandsupplycompany.com/resources/regulator-sizing-tools/general'
  });
  return dom;
}

function driver(dom) {
  const doc = dom.window.document;
  const Ev = dom.window.Event;
  const set = (id, v) => {
    const el = doc.getElementById('usg-' + id);
    el.value = String(v);
    el.dispatchEvent(new Ev('change', { bubbles: true }));
  };
  const radio = (name, v) => {
    for (const el of doc.querySelectorAll('input[name="usg-' + name + '"]')) {
      el.checked = el.value === v;
      if (el.checked) el.dispatchEvent(new Ev('change', { bubbles: true }));
    }
  };
  return {
    doc, set, radio,
    fill(input) {
      if (input.inlet !== undefined) set('inlet', input.inlet);
      if (input.outlet !== undefined) set('outlet', input.outlet);
      if (input.flow !== undefined) set('flow', input.flow);
      if (input.min_flow !== undefined) set('minflow', input.min_flow);
      if (input.maop !== undefined) set('maop', input.maop);
      if (input.inlet_units) set('inlet-units', input.inlet_units);
      if (input.outlet_units) set('outlet-units', input.outlet_units);
      if (input.flow_units) set('flow-units', input.flow_units);
      if (input.pipe_size) set('pipesize', PIPE_OPTIONS.indexOf(input.pipe_size));
      if (input.opp_required) {
        radio('opp', 'Yes');
        radio('opppref', input.opp_pref === 'Monitor' ? 'Monitor regulator' : 'IRV (Internal Relief Valve)');
        if (input.irv_pressure !== undefined) set('irv', input.irv_pressure);
      }
      if (input.partial_irv) radio('partial', 'Yes');
      if (input.high_efficiency) {
        radio('higheff', 'Yes');
        if (input.high_efficiency_pct !== undefined) set('pload', input.high_efficiency_pct);
      }
      if (input.override_oversize) {
        radio('override', 'Yes');
        if (input.oversize_pct !== undefined) set('oversize', input.oversize_pct);
      }
      if (input.prefer_combustion) radio('combust', 'Yes');
      if (input.gas_type) set('gastype', input.gas_type);
      if (input.specific_gravity !== undefined) set('sg', input.specific_gravity);
      if (input.high_altitude) {
        radio('elevation', 'Yes');
        if (input.atmospheric_pressure !== undefined) set('patm', input.atmospheric_pressure);
      }
    },
    async run() {
      doc.getElementById('usg-run-btn').click();
      const out = doc.getElementById('usg-output');
      for (let i = 0; i < 100; i++) {
        await new Promise(r => setTimeout(r, 20));
        if (!out.querySelector('.usg-spinner')) break;
      }
      return {
        text: out.textContent,
        codes: Array.from(out.querySelectorAll('.usg-code')).map(c => c.textContent.trim()),
        adjustments: Array.from(out.querySelectorAll('.usg-table tbody tr'))
          .map(tr => Array.from(tr.querySelectorAll('td')).map(td => td.textContent.trim())),
        hasError: !!out.querySelector('.usg-error'),
        hasSuccess: !!out.querySelector('.usg-success'),
        hasWarning: !!out.querySelector('.usg-warning'),
        hasInfo: !!out.querySelector('.usg-info'),
        hasPdfBtn: !!doc.getElementById('usg-pdf-btn')
      };
    }
  };
}

(async () => {
  console.log('\n== block does not contain the algorithm ==');
  check('no capacity data in the block', blockHtml.indexOf('interpolate_capacity') === -1);
  check('block is small', blockHtml.length < 60000, blockHtml.length + ' bytes');
  check('loads the algorithm from jsDelivr', /cdn\.jsdelivr\.net\/gh\/[^"]+\/dist\/usg-all-models\.js/.test(blockHtml));

  console.log('\n== the page displays exactly what Python computes ==');
  for (const fx of fixtures) {
    const dom = makePage();
    const d = driver(dom);
    d.fill(fx.input);
    const got = await d.run();
    const want = fx.expected;
    const label = fx.name;

    if (!want.ok) {
      check(label + ' - shows the same errors', want.errors.every(e => got.text.indexOf(e) !== -1) && got.hasError,
        got.text.slice(0, 200));
      continue;
    }
    if (!want.selected) {
      check(label + ' - reports no match', got.hasError && got.text.indexOf(want.message) !== -1, got.text.slice(0, 200));
      continue;
    }

    const problems = [];
    if (!got.hasSuccess) problems.push('no success box');
    for (const f of want.selection) {
      if (got.text.indexOf(f.label + ': ' + f.value) === -1) problems.push('missing ' + f.label + '=' + f.value);
    }
    if (want.capacity && got.text.indexOf('Calculated Capacity (CFH): ' + want.capacity) === -1) {
      problems.push('capacity ' + want.capacity);
    }
    if (JSON.stringify(got.codes) !== JSON.stringify(want.part_numbers)) {
      problems.push('part numbers ' + JSON.stringify(got.codes) + ' vs ' + JSON.stringify(want.part_numbers));
    }
    const wantAdj = want.adjustments.map(a => [a.label, a.value]);
    if (JSON.stringify(got.adjustments) !== JSON.stringify(wantAdj)) {
      problems.push('adjustments ' + JSON.stringify(got.adjustments) + ' vs ' + JSON.stringify(wantAdj));
    }
    for (const w of want.warnings) {
      if (got.text.indexOf(w) === -1) problems.push('warning ' + w);
    }
    if (want.pipe_note && got.text.indexOf(want.pipe_note) === -1) problems.push('pipe note');
    if (!got.hasPdfBtn) problems.push('no PDF button');

    check(label, problems.length === 0, problems.join('; '));
  }

  console.log('\n== behaviour when the algorithm fails to load ==');
  {
    const dom = makePage({ omitAlgorithm: true });
    const d = driver(dom);
    d.fill({ inlet: 10, outlet: 2, flow: 500 });
    const got = await d.run();
    check('shows a clear message, does not hang', got.hasError &&
      got.text.indexOf('could not be loaded') !== -1, got.text.slice(0, 200));
  }

  console.log('\n== form behaviour ==');
  {
    const dom = makePage();
    const d = driver(dom);
    const doc = d.doc;
    check('required labels start red', doc.getElementById('usg-label-inlet').classList.contains('usg-req'));
    d.set('inlet', 10);
    check('label clears when filled', !doc.getElementById('usg-label-inlet').classList.contains('usg-req'));
    check('IRV block hidden initially', doc.getElementById('usg-opp-yes-block').style.display === 'none');
    d.radio('opp', 'Yes');
    check('opp Yes reveals preference', doc.getElementById('usg-opp-yes-block').style.display === '');
    check('IRV psi shown for IRV default', doc.getElementById('usg-irv-input-block').style.display === '');
    d.radio('opppref', 'Monitor regulator');
    check('monitor hides IRV psi', doc.getElementById('usg-irv-input-block').style.display === 'none');
    d.radio('higheff', 'Yes');
    check('% load slider appears', doc.getElementById('usg-pload-block').style.display === '');
    d.set('pload', 60);
    check('slider badge updates', doc.getElementById('usg-pload-val').textContent === '60');
    d.set('gastype', 'Other');
    check('specific gravity appears', doc.getElementById('usg-sg-block').style.display === '');
    d.radio('elevation', 'Yes');
    check('atmospheric pressure appears', doc.getElementById('usg-patm-block').style.display === '');
    check('no +/- steppers', doc.querySelectorAll('.usg-step').length === 0);

    const icons = doc.querySelectorAll('.usg-help');
    check('7 info tooltips', icons.length === 7, icons.length);
    const tip = doc.querySelector('.usg-tipbox');
    icons[0].dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true, cancelable: true }));
    check('tooltip opens on tap', tip.classList.contains('usg-show'));
    doc.body.dispatchEvent(new dom.window.MouseEvent('click', { bubbles: true, cancelable: true }));
    check('tooltip closes on outside tap', !tip.classList.contains('usg-show'));
  }

  console.log(`\n${pass} passed, ${fail} failed\n`);
  process.exit(fail ? 1 : 0);
})();
